# Generated by Django 3.0.5 on 2020-05-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interface', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='Password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='channel',
            name='coverage',
            field=models.ImageField(default='default.jpg', upload_to='images'),
        ),
    ]
