# Generated by Django 3.0.5 on 2020-05-11 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Interface', '0002_auto_20200511_0411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='username',
            new_name='user',
        ),
    ]
