# Generated by Django 3.0.5 on 2020-05-11 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Interface', '0004_delete_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Password', models.CharField(max_length=50)),
                ('IP', models.GenericIPAddressField()),
                ('PortNumber', models.IntegerField()),
                ('Cameranum', models.IntegerField()),
                ('Cameramodel', models.CharField(max_length=50)),
                ('Description', models.TextField(max_length=200)),
                ('coverage', models.ImageField(default='default.jpg', upload_to='images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
