# Generated by Django 2.2.7 on 2020-08-11 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Interface', '0006_auto_20200511_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_model', models.CharField(max_length=40)),
                ('rtsp_url', models.ImageField(default='default.jpg', upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
                ('IP', models.CharField(max_length=15, unique=True)),
                ('portNum', models.CharField(max_length=5)),
                ('cameraNum', models.CharField(max_length=3)),
                ('description', models.CharField(max_length=255, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('coordinates', models.CharField(default='', max_length=600)),
                ('names', models.CharField(default='', max_length=600)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_camera', to='Interface.Camera')),
            ],
        ),
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_name', models.CharField(max_length=40)),
                ('captureTime', models.DateTimeField()),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Interface.Channel')),
            ],
        ),
        migrations.CreateModel(
            name='Heatmap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topColor', models.CharField(default='', max_length=255)),
                ('bottomColor', models.CharField(default='', max_length=255)),
                ('topLeftX', models.IntegerField(default=0)),
                ('topLeftY', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('dwellingTime', models.IntegerField(default=-1)),
                ('zoneArea', models.IntegerField(default=-1)),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Interface.Frame')),
            ],
        ),
        migrations.DeleteModel(
            name='ChannelDetail',
        ),
    ]
