# Generated by Django 2.2.7 on 2020-08-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interface', '0007_auto_20200811_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='camera_model',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
