# Generated by Django 2.2.7 on 2020-09-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interface', '0008_auto_20200812_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='directions',
            field=models.CharField(default='', max_length=600),
        ),
    ]
