# Generated by Django 2.2.7 on 2020-09-10 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Interface', '0009_channel_directions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topColor', models.CharField(default='', max_length=255)),
                ('bottomColor', models.CharField(default='', max_length=255)),
                ('topLeftX', models.IntegerField(default=0)),
                ('topLeftY', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('direction', models.IntegerField(default=-1)),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Interface.Frame')),
            ],
        ),
    ]
